package alborz

import (
	"encoding/json"
)

// mustJSON encodes what the worker's source needs as a literal. The
// values are paths this process built, so an error here is a bug.
func mustJSON(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(b)
}

// serviceWorker is the whole worker, with the cache name and the shell
// it holds filled in.
//
// It keeps two things. The shell - a stylesheet and three scripts,
// already stamped with a digest - is what makes the application start
// instantly, and is kept until the next one replaces it. The pages the
// reader has opened are kept so that a train tunnel or a server restart
// leaves them something to read: the network is always asked first, and
// a saved page answers only when it does not. A saved page is somebody's
// mail on a disk, which is what alborz long refused to write, so it is
// bounded three ways: signing in or out deletes every one, none is
// served after pagesDays, and no more than pagesMax are held.
const serviceWorker = `// Generated by alborz. Cache version %[1]s.
const CACHE = "alborz-shell-%[1]s";
const PAGES = "alborz-pages";
const SHELL = %[2]s;
const PAGES_MAX = 200;
const PAGES_DAYS = 7;
// How long the network is given before a saved copy answers. A phone on
// a dead connection does not fail a request, it lets it hang.
const NETWORK_WAIT = 5000;
const SAVED_AT = "X-Alborz-Saved";

self.addEventListener("install", event => {
	event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(SHELL)).then(() => self.skipWaiting()));
});

// A new version of the shell means a new cache name; the old ones go,
// so a stale stylesheet cannot outlive a deploy. The pages stay: they
// belong to the reader, not to a version.
self.addEventListener("activate", event => {
	event.waitUntil(caches.keys().then(names =>
		Promise.all(names.filter(name => name !== CACHE && name !== PAGES).map(name => caches.delete(name)))
	).then(() => self.clients.claim()));
});

// Whether the last page came from the network or from here. Pages ask
// when they load and are told when it changes, so the notice that says
// "offline" is never a guess made from the radio's state.
// What the last page request met: "" an answer, "offline" a request
// that failed, "slow" one given up on. The worker says which, since a
// server that takes its time is not a connection that is gone.
let met = "";
const word = () => ({ alborzOffline: met !== "", alborzSlow: met === "slow" });
const tell = async state => {
	if (state === met) {
		return;
	}
	met = state;
	for (const client of await self.clients.matchAll({ includeUncontrolled: true })) {
		client.postMessage(word());
	}
};
self.addEventListener("message", event => {
	if (event.data === "alborz-offline?" && event.source) {
		event.source.postMessage(word());
	}
});

// A fragment and the page it belongs to share a URL and differ in what
// htmx asked for, so the target is part of the key. A boosted click and
// a reload ask for the same document, and share one.
const pageKey = request => {
	const url = new URL(request.url);
	const target = request.headers.get("HX-Target");
	if (target) {
		url.searchParams.set("__hx-target", target);
	}
	return url.href;
};

const savePage = async (key, response) => {
	const headers = new Headers(response.headers);
	headers.set(SAVED_AT, String(Date.now()));
	const cache = await caches.open(PAGES);
	await cache.put(key, new Response(await response.blob(), { status: response.status, headers }));
	const keys = await cache.keys();
	await Promise.all(keys.slice(0, Math.max(0, keys.length - PAGES_MAX)).map(old => cache.delete(old)));
};

const savedPage = async key => {
	const cache = await caches.open(PAGES);
	const saved = await cache.match(key);
	if (saved && Date.now() - Number(saved.headers.get(SAVED_AT)) > PAGES_DAYS * 86400000) {
		await cache.delete(key);
		return undefined;
	}
	return saved;
};

// The network first, bounded when there is something to fall back on;
// what it answers is kept when it is a page. Any answer at all means
// the server is there, whatever its status.
const page = async (event, ask) => {
	const key = pageKey(event.request);
	const saved = await savedPage(key);
	const patience = new AbortController();
	// A search is as slow as the server's index, and no saved copy of
	// one is worth more than its answer: it is waited for.
	const bounded = saved && !new URL(event.request.url).searchParams.has("query");
	const timer = bounded ? setTimeout(() => patience.abort(), NETWORK_WAIT) : 0;
	try {
		const answer = await ask(patience.signal);
		clearTimeout(timer);
		tell("");
		// Not the sign-in page: it is what a purge leaves behind, and
		// offline it would answer for the page the reader asked for.
		// Nor the pages of a visit that locks: what is saved is read
		// offline with no server to ask for the passkey, so such a visit
		// keeps nothing, and what it kept before it had a lock goes.
		if ((answer.headers.get("Cache-Control") || "").includes("no-store")) {
			event.waitUntil(caches.delete(PAGES));
		} else if (answer.ok && new URL(event.request.url).pathname !== "/login" &&
			(answer.headers.get("Content-Type") || "").startsWith("text/html")) {
			event.waitUntil(savePage(key, answer.clone()));
		}
		return answer;
	} catch (failure) {
		clearTimeout(timer);
		tell(patience.signal.aborted ? "slow" : "offline");
		if (saved) {
			return saved;
		}
		throw failure;
	}
};

self.addEventListener("fetch", event => {
	const request = event.request;
	const url = new URL(request.url);
	if (url.origin !== self.location.origin) {
		return;
	}
	// Signing in or out ends what was saved: the pages were one
	// reader's, and the next one at this browser may be another. The
	// page of browsers signed in is among them because it signs this
	// one out too, and a POST's answer is a redirect the worker cannot
	// read to tell which browser it was.
	if (request.method === "POST" && ["/login", "/logout", "/unlock/leave", "/settings/sessions"].includes(url.pathname)) {
		event.waitUntil(caches.delete(PAGES));
		return;
	}
	if (request.method !== "GET") {
		return;
	}
	// The shell is stamped with a digest, so a hit is the right file by
	// construction and a miss fetches and keeps the new one.
	if (url.pathname.startsWith("/assets/")) {
		event.respondWith(caches.match(request).then(hit => hit || fetch(request).then(answer => {
			if (answer.ok) {
				const copy = answer.clone();
				caches.open(CACHE).then(cache => cache.put(request, copy));
			}
			return answer;
		})));
		return;
	}
	// Never from the browser's own store: pages carry no cache headers,
	// so a heuristically fresh copy would answer a reload with
	// yesterday's page - which in an installed window, where there is
	// no address bar to force the issue, looks like an application that
	// cannot be updated.
	if (request.mode === "navigate") {
		// redirect manual, not follow: a response a worker followed
		// cannot be handed back for a navigation, and most of alborz's
		// pages answer a redirect - a post that lands, a URL made
		// canonical. Manual hands the browser the redirect itself and
		// it navigates again, through here, fresh.
		event.respondWith(
			// A page never saved fails as any page does offline: the
			// browser says so in its own words.
			page(event, signal => fetch(request.url, { cache: "reload", credentials: "same-origin", redirect: "manual", signal }))
		);
		return;
	}
	// What htmx asks for: a boosted page or a fragment of one. The
	// event stream and downloads are neither, and pass untouched.
	if (request.headers.get("HX-Request") === "true") {
		event.respondWith(page(event, signal => fetch(request, { signal })));
	}
});
`
