package alborz

import (
	"encoding/json"
)

// offlinePath is where the page shown without a network lives. It is
// public, like the manifest, and names no account.
const offlinePath = "/offline"

// mustJSON encodes what the worker's source needs as a literal. The
// values are paths this process built, so an error here is a bug.
func mustJSON(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(b)
}

// serviceWorker is the whole worker, with the cache name, the shell it
// holds and the offline page filled in.
//
// It caches the shell and nothing else. Every page alborz serves is
// somebody's mail, and mail written to disk by a browser outlives the
// session, the logout and the reader; the shell is a stylesheet and
// three scripts, already stamped with a digest, so keeping them is both
// safe and the whole of what makes the application start instantly.
// A navigation always goes to the network, and only a failed one is
// answered at all - with the offline page, which says so.
const serviceWorker = `// Generated by alborz. Cache version %[1]s.
const CACHE = "alborz-shell-%[1]s";
const SHELL = %[2]s;
const OFFLINE = %[3]q;

self.addEventListener("install", event => {
	event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(SHELL)).then(() => self.skipWaiting()));
});

// A new version of the shell means a new cache name; the old ones go,
// so a stale stylesheet cannot outlive a deploy.
self.addEventListener("activate", event => {
	event.waitUntil(caches.keys().then(names =>
		Promise.all(names.filter(name => name !== CACHE).map(name => caches.delete(name)))
	).then(() => self.clients.claim()));
});

self.addEventListener("fetch", event => {
	const request = event.request;
	if (request.method !== "GET") {
		return;
	}
	const url = new URL(request.url);
	if (url.origin !== self.location.origin) {
		return;
	}
	// The shell is stamped with a digest, so a hit is the right file by
	// construction and a miss fetches and keeps the new one.
	if (url.pathname.startsWith("/assets/")) {
		event.respondWith(caches.match(request).then(hit => hit || fetch(request).then(answer => {
			if (answer.ok) {
				const copy = answer.clone();
				caches.open(CACHE).then(cache => cache.put(request, copy));
			}
			return answer;
		})));
		return;
	}
	// Everything else is somebody's mail. It is never kept, and it is
	// never taken from the browser's own store either: pages carry no
	// cache headers, so a heuristically fresh copy would answer a
	// reload with yesterday's page - which in an installed window,
	// where there is no address bar to force the issue, looks like an
	// application that cannot be updated. A page that cannot be
	// fetched is answered with the one page that is true without a
	// network.
	if (request.mode === "navigate") {
		// redirect manual, not follow: a response a worker followed
		// cannot be handed back for a navigation, and most of alborz's
		// pages answer a redirect - a post that lands, a URL made
		// canonical. Manual hands the browser the redirect itself and
		// it navigates again, through here, fresh.
		event.respondWith(
			fetch(request.url, { cache: "reload", credentials: "same-origin", redirect: "manual" })
				.catch(() => caches.match(OFFLINE))
		);
	}
});
`
